version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          - BUNDLER_VERSION: 2.1.4
          - RAILS_ENV: 'test'
      - image: circleci/mysql:8.0.22
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

workflows:
  test_workflow:
    jobs:
      - build
